"""Generate `README.md` for every artifact bundle.

The README is a navigation file: what is in the bundle, where each piece
lives, how the pieces relate. It is the entry point for someone opening
the zip cold. It is NOT the email to the professor and it is NOT an audit
report.

Audit / red-flag analysis lives in a separate FAILURES.md generated by a
post-hoc script for individual deliveries; that file is not produced by
the pipeline because it requires reviewer judgment after the run finishes.

Inputs (all minimal; no audit data needed):
  - run_id, manual_name, git_sha, started_at, wall_clock_sec
  - output_dir (Path to the bundle; reads file sizes for the legend)
  - labeled_chunks (list of dicts; used to surface chunk count + label total)
  - stats (cost/tokens summary from run_gen7_extraction return value)
  - stage3_artifact (for the headline Stage 3 numbers)
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _size(path: Path) -> str:
    try:
        b = path.stat().st_size
        if b < 1024:
            return f"{b} B"
        if b < 1024 * 1024:
            return f"{b/1024:.1f} KB"
        return f"{b/(1024*1024):.1f} MB"
    except FileNotFoundError:
        return "(missing)"


def _rel_size(output_dir: Path, relative: str) -> str:
    return _size(output_dir / relative)


def build_readme(
    output_dir: Path,
    run_id: str,
    manual_name: str,
    git_sha: str,
    started_at: str,
    wall_clock_sec: float,
    labeled_chunks: list[dict],
    stats: dict[str, Any],
    audit_report: dict[str, Any] | None = None,  # accepted for back-compat; unused
    data_flow: dict[str, Any] | None = None,     # accepted for back-compat; unused
    stage3_artifact: dict[str, Any] | None = None,
) -> str:
    total_chunks = len(labeled_chunks)
    total_labels = sum(len(c.get("labels", []) or []) for c in labeled_chunks)

    lines: list[str] = []

    # ----- Header -----
    lines.append(f"# CHW Navigator: {manual_name}")
    lines.append("")
    lines.append("Open this README first. It is the navigation file for everything in the zip.")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| Run ID | `{run_id}` |")
    lines.append(f"| Source manual | {manual_name} |")
    lines.append(f"| Model | Claude Opus 4.6 (temperature 0, all three stages) |")
    lines.append(f"| Git SHA | `{git_sha}` |")
    lines.append(f"| Started | {started_at} |")
    lines.append(f"| Wall clock | {wall_clock_sec:.1f}s |")
    lines.append(f"| Chunks | {total_chunks} |")
    lines.append(f"| Total labels (raw) | {total_labels:,} |")
    if stage3_artifact:
        lines.append(f"| Deduped labels into REPL | {stage3_artifact.get('deduped_label_count', '?'):,} |")
    if "total_cost_usd" in stats:
        lines.append(f"| Total cost (Anthropic) | ${stats['total_cost_usd']:.2f} |")
    lines.append("")

    # ----- Quick start -----
    lines.append("## Quick start (where to look first)")
    lines.append("")
    lines.append("If you want to **see the decision logic the model produced**, open `clinical_logic.json` and `flowchart.png`. The JSON is the source of truth; the PNG is a one-page overview.")
    lines.append("")
    lines.append("If you want to **deploy the form**, take `form.xlsx` (XLSForm) and `clinical_logic.dmn` (DMN 1.3 XML). They are derived from the JSON via deterministic Python converters.")
    lines.append("")
    lines.append("If you want to **review what the LLM saw and said**, open `system_prompt.md` (the full prompt bundle, all three stages) and `stage3_repl.json` (the actual Stage 3 input and final output).")
    lines.append("")
    lines.append("If you want to **trace a rule back to the manual**, every entry in `clinical_logic.json` carries a `source_section_id` and `source_quote`. The full reconstructed manual text is in `reconstructed_guide.txt`.")
    lines.append("")
    lines.append("If you want **per-variable scope and lifecycle** (which module collects what, what depends on what), open `artifacts/data_flow.json`.")
    lines.append("")
    lines.append("If a separate `FAILURES.md` is in this zip, it contains the post-run audit (auto-registered ids, orphan variables, underproduced chunks, known issues from this specific run). Read it after the README, before drawing conclusions.")
    lines.append("")

    # ----- How the pipeline produced this -----
    lines.append("## How this bundle was produced")
    lines.append("")
    lines.append("Three Opus calls per chunk-or-session, all temperature 0, against the same content-hashed PDF.")
    lines.append("")
    lines.append("1. **Chunk** (deterministic Python). The cached PDF JSON is split into ~2K-token micro-chunks. No LLM.")
    lines.append("2. **Stage 1A: Label** (Opus, one call per chunk, parallel). Each chunk gets every clinical item annotated with id + type + span + quote_context.")
    lines.append("3. **Stage 1B: QC** (Opus, one call per chunk). Drops hallucinated labels; never adds new ones.")
    lines.append("4. **Dedupe** (deterministic Python). Exact-string dedup on `(id, type)`.")
    lines.append("5. **Stage 3: REPL compile** (Opus, one Python REPL session). Reads the deduped inventory + the full reconstructed guide as cached blocks; emits the seven artifacts in DAG order: supply_list -> variables -> predicates -> modules -> router -> integrative -> phrase_bank.")
    lines.append("6. **Reconcile** (deterministic Python). Cross-references every id; auto-registers anything Phase B referenced but Phase A missed (`_auto_registered: true`).")
    lines.append("7. **Derive** (deterministic Python). Builds `data_flow.json` and the converters (DMN XML, XLSForm, Mermaid, CSV).")
    lines.append("")
    lines.append("The full prompts for Stage 1A, Stage 1B, and Stage 3 are in `system_prompt.md`. The naming codebook (which prefixes mean what) is its own section in that file.")
    lines.append("")

    # ----- File map -----
    lines.append("## File map")
    lines.append("")

    lines.append("### Outputs you would deploy or show a clinician")
    lines.append("")
    lines.append("| File | What it is | Size |")
    lines.append("|------|------------|------|")
    for name, desc in [
        ("clinical_logic.json", "The decision model in review-friendly JSON. Source of truth."),
        ("clinical_logic.dmn",  "Same model, DMN 1.3 XML. Deployable to any DMN engine."),
        ("form.xlsx",           "CHT-deployable XLSForm. Derived from clinical_logic.json."),
        ("flowchart.png",       "One-page Mermaid render: router -> modules -> integrative."),
        ("flowchart.md",        "Mermaid source for `flowchart.png`. Re-render with mmdc or paste into mermaid.live."),
        ("predicates.csv",      "Flat CSV of every predicate. Easier to scan than the JSON."),
        ("phrases.csv",         "Flat CSV of every phrase the CHW says."),
    ]:
        lines.append(f"| `{name}` | {desc} | {_rel_size(output_dir, name)} |")
    lines.append("")

    lines.append("### Per-phase emitted artifacts (the seven checkpoints)")
    lines.append("")
    lines.append("Each of these is the Stage 3 REPL's output for one DAG step. Read in this order to follow the model's reasoning.")
    lines.append("")
    lines.append("| File | What it is | Size |")
    lines.append("|------|------------|------|")
    for name, desc in [
        ("supply_list", "Equipment + consumables the CHW must have on hand."),
        ("variables",   "Every runtime input: symptoms, exam findings, measurements, demographics."),
        ("predicates",  "Boolean predicates computed from variables (e.g. `p_fast_breathing`)."),
        ("modules",     "One decision table per clinical module (assess, diarrhoea, fever, etc.)."),
        ("router",      "The traffic cop: priority routing across modules. Row 0 is the priority-exit short-circuit."),
        ("integrative", "Cross-module merge rules. Often minimal because the router handles cross-module flow via flags."),
        ("phrase_bank", "Every phrase the CHW says: questions, diagnoses, treatments, referrals, advice."),
    ]:
        lines.append(f"| `artifacts/{name}.json` | {desc} | {_rel_size(output_dir, 'artifacts/' + name + '.json')} |")
    lines.append("")
    lines.append("Two more derived artifacts in the same directory:")
    lines.append("")
    lines.append("| File | What it is | Size |")
    lines.append("|------|------------|------|")
    for name, desc in [
        ("data_flow",              "Per-variable scope (universal / module-scoped / cross_module / derived / orphan), source (ask/observe/measure/history), and which modules collect vs use it."),
        ("referential_integrity",  "Cross-reference audit: every id used in modules/router/predicates must be declared. Any gap is auto-registered with `_auto_registered: true`. Reads before-state, what was added, after-state."),
    ]:
        lines.append(f"| `artifacts/{name}.json` | {desc} | {_rel_size(output_dir, 'artifacts/' + name + '.json')} |")
    lines.append("")

    lines.append("### Logging and traceability")
    lines.append("")
    lines.append("| File | What it is | Size |")
    lines.append("|------|------------|------|")
    for name, desc in [
        ("system_prompt.md",         "Full multi-stage system prompt: Stage 1A labeling, Stage 1B QC, Stage 3 REPL compile, plus the naming codebook. This is what Opus actually saw."),
        ("stage3_repl.json",         "The Stage 3 REPL session: full system prompt + cached source guide + cached deduped labels + initial user message + final response + iteration count."),
        ("labeled_chunks.json",      "Stage 1 per-chunk output: labels per chunk + `_labeling_meta` with stage1a/stage1b token counts, response chars, and the `diff_chars` red-flag signal."),
        ("deduped_labels.json",      "Consolidated label set after exact-string dedup. The inventory the REPL compiled from."),
        ("reconstructed_guide.txt",  "The full text Opus saw at labeling time. Built from the chunker's input, not from Opus's echo. Use this to verify any label's provenance."),
        ("scratchpad.md",            "Step-by-step pipeline execution journal."),
        ("test_suite.json",          "Generated boundary + scenario test cases from the label inventory."),
        ("final_dmn.validator.json", "Catcher report on the final DMN. `passed: true` plus boundary-condition warnings."),
    ]:
        lines.append(f"| `{name}` | {desc} | {_rel_size(output_dir, name)} |")
    lines.append("")

    lines.append("### Internal (not reviewer-facing)")
    lines.append("")
    lines.append("| File | What it is | Size |")
    lines.append("|------|------------|------|")
    lines.append(f"| `chunk_difficulty.json` | Per-chunk complexity score the labeling scheduler used. No clinical content. | {_rel_size(output_dir, 'chunk_difficulty.json')} |")
    lines.append("")

    # ----- Cross-references -----
    lines.append("## How the files fit together")
    lines.append("")
    lines.append("```")
    lines.append("    PDF -> guide JSON (cached in Neon)")
    lines.append("                 |")
    lines.append("                 v")
    lines.append("        chunker  -> 21 micro-chunks  -> reconstructed_guide.txt")
    lines.append("                                       (full text Opus saw)")
    lines.append("                 |")
    lines.append("                 v")
    lines.append("    Stage 1A label (Opus, one call per chunk, in parallel)")
    lines.append("    Stage 1B QC   (Opus, one call per chunk)")
    lines.append("                 |")
    lines.append("                 v")
    lines.append("        labeled_chunks.json  ----- per-chunk metadata + labels")
    lines.append("                 |")
    lines.append("                 v")
    lines.append("        deduped_labels.json  ----- exact-string dedup, no LLM")
    lines.append("                 |")
    lines.append("                 v")
    lines.append("    Stage 3 REPL (Opus, one Python session)")
    lines.append("                 |")
    lines.append("                 v")
    lines.append("        artifacts/{supply_list, variables, predicates,")
    lines.append("                   modules, router, integrative, phrase_bank}.json")
    lines.append("                 |")
    lines.append("                 v")
    lines.append("        referential_integrity.json + data_flow.json")
    lines.append("        (deterministic post-process; auto-fills registry drift)")
    lines.append("                 |")
    lines.append("                 v")
    lines.append("        clinical_logic.json")
    lines.append("                 |")
    lines.append("       +---------+---------+----------+")
    lines.append("       v         v         v          v")
    lines.append("  clinical_   form.xlsx flowchart  predicates.csv")
    lines.append("  logic.dmn  (XLSForm)  .png/.md   phrases.csv")
    lines.append("```")
    lines.append("")
    lines.append("Every output below `clinical_logic.json` is a deterministic transform of it. If you change the JSON and re-run the converters, the DMN, XLSForm, flowchart, and CSVs change in lockstep.")
    lines.append("")

    return "\n".join(lines)
